import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="h-screen flex overflow-hidden">
        <Sidebar />
        <div className="flex-1 overflow-auto pb-content px-content">
          {/* <Header /> */}
          {children}
        </div>
      </div></body>
    </html>
  );
}




